### ISSUE TITLE
Umlaut returns 400

### ISSUE THREAD

**Issue by anlausch** [scienceai/crossref#5]
Hi all,

I just noticed that whenever I place a query containing an "umlaut", I just receive a 400 error.

Example:

- Direct use of the Crossref REST API (returns 200):
https://api.crossref.org/works?query.container-title=Gabe%20fu%CC%88r%20die%20Mitglieder

- My code using the node.js wrapper:
```
    crossref.works({"query.container-title": "Gabe für die Mitglieder"}, (err, objs, nextOpts, done) => {
        if (err) { // is filled with 400
            errorlog.error(err);
            return callback(err, null);
        } ..
```
Of course, the "ü" is URL encoded in my example when using the API directly, but so it is with spaces, which I also do not need to encode before using the node.js wrapper.
I also tested it with other "umlaute" such as "ö" or "ä" and I experience the same behavior.

Edit: When I escape the string, the err is not 400 anymore but 500, which makes sense, because it is probably escaped twice.
 
Can you help on this?
Thanks in advance

**Comment by sballesteros** [comment]
cc @darobin

**Comment by darobin** [comment]
I added your code as a test file and it works without the slightest problem. I tried updating the dependencies to see if that caused the problem but it still worked. Is it possible you have some form of proxy?

I would share the changes I made, but I no longer have write access to this repo.

**Comment by sballesteros** [comment]
@darobin lmk if you want write access, otherwise happy to merge PR too.

**Comment by anlausch** [comment]
I think it was actually a proxy problem. Thanks!
